# Generated by Django 4.1 on 2022-08-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_author_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
